# Generated by Django 3.1.7 on 2022-06-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersdata', '0005_auto_20220618_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='Введите имя', max_length=1000, verbose_name='Имя пользователя'),
        ),
    ]
