# Generated by Django 3.1.7 on 2022-06-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersdata', '0006_auto_20220618_0214'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
